name: Test Jupyter Notebook

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbval

      - name: Run Jupyter notebook and test for errors
        run: |
          py.test --nbval-lax notebook.ipynb
